import { FederatedServer } from "./federated-server.interface";


export const federatedServerList: FederatedServer[] = [
    {
        name: 'DRSGME/WhyDRS Lemmy',
        statusPositive: true,
        displayUrl: 'lemmy.whynotdrs.org',
        fullUrl: 'https://lemmy.whynotdrs.org/',
        userCount: 200,
        serverStatus: '',
        drsStatus: '',
        adminEmail: '',
        adminCreds: [
            {credName: 'DRSGME.org team', credUrl: 'https://www.drsgme.org'},
        ],
        drsEvidenceLink: '',
        registrationStatus: 'OPEN',
        registrationLink: '',
        implementation: 'Lemmy',
        serverLocation: '',
        thumbnailFile: 'assets/drsgmewhydrs-thumb.png',
        serverDescription: '',
        exploreLink: 'https://lemmy.whynotdrs.org/',
        aboutLink: 'https://lemmy.whynotdrs.org/',
        ownerIsExpanded: false,
    },
    {
        name: 'GMESTOCK',
        statusPositive: true,
        displayUrl: 'gmestock.com',
        fullUrl: 'https://gmestock.com/',
        userCount: 2,
        serverStatus: '',
        drsStatus: '',
        adminEmail: '',
        adminCreds: [
            {credName: '@pigUw', credUrl: 'https://gmestock.com/u/pigUw'},
        ],
        drsEvidenceLink: '',
        registrationStatus: 'OPEN',
        registrationLink: '',
        implementation: 'Lemmy',
        serverLocation: '',
        thumbnailFile: 'assets/gmestockdotcom-thumb.png',
        serverDescription: '',
        exploreLink: 'https://gmestock.com/',
        aboutLink: 'https://gmestock.com/',
        ownerIsExpanded: false,
    },
    {
        name: 'Superstork',
        statusPositive: true,
        displayUrl: 'www.superstork.org',
        fullUrl: 'https://www.superstork.org',
        userCount: 150,
        serverStatus: '',
        drsStatus: '',
        adminEmail: 'superstork_admin@protonmail.com',
        adminCreds: [
            {credName: '@jersan', credUrl: 'https://www.superstork.org/@jersan'},
            {credName: 'u/jersan', credUrl: 'https://www.reddit.com/user/jersan'},
        ],
        drsEvidenceLink: 'https://www.reddit.com/user/jersan/comments/108bnm1/xxxx_booked/',
        registrationStatus: 'OPEN',
        registrationLink: '',
        implementation: 'Mastodon',
        serverLocation: 'Toronto, Canada',
        thumbnailFile: 'assets/superstork-thumb.png',
        serverDescription: 'The superstork protects the nest. This is a place for theoretical discussions about business and stocks - specifically GameStop stock ($GME). Opinions and memes welcome.',
        exploreLink: 'https://www.superstork.org/public/local',
        aboutLink: 'https://www.superstork.org/about',
        ownerIsExpanded: false,
    },
    {
        name: 'The Cyber Network',
        statusPositive: true,
        displayUrl: 's.thecybernetwork.us',
        fullUrl: 'https://s.thecybernetwork.us',
        userCount: 3,
        serverStatus: '',
        drsStatus: '',
        adminEmail: 'contact@thecybernetwork.us',
        adminCreds: [
            {credName: '@venivv', credUrl: 'https://s.thecybernetwork.us/@venivv'},
            {credName: 'u/Anon_0365Admin', credUrl: 'https://www.reddit.com/user/Anon_0365Admin'},
        ],
        drsEvidenceLink: 'https://www.reddit.com/r/Superstonk/comments/xvr1bl/moving_this_over_from_gmeorphans/',
        registrationStatus: 'BY_INVITE',
        registrationLink: 'https://s.thecybernetwork.us/invite/Fjwriv6R',
        implementation: 'Mastodon',
        serverLocation: '',
        thumbnailFile: 'assets/cybernetwork-thumb.png',
        serverDescription: 'A place for those of us that want to be a part of a decentralized future. We are gamers, techs, drone pilots, and a multitude of other hobbyists.',
        exploreLink: 'https://s.thecybernetwork.us/public/local',
        aboutLink: 'https://s.thecybernetwork.us/about',
        ownerIsExpanded: false,
    },
]